### PR TITLE
Adding bitHound

### PR DESCRIPTION
**Pull request by carlosperez**
We use Polymer extensively (~14 custom elements) for our front-end. We'd love to showcase it here.

- [x] Add blog post content
- [x] Include screenshot

### CODE REVIEW

**Comment by fastdivision** [comment]
Very nice. Thanks for your contribution! :+1:

**Comment by carlosperez** [comment]
Thanks for merging this in! Just curious when it will be live?

**Comment by fastdivision** [comment]
@carlosperez It's up now :-)

**Comment by carlosperez** [comment]
Awesome! Thank you!

**Pull request merged**
