### PR TITLE
Added Sid Lee Paris Dashboard

### PR DESCRIPTION
**Pull request by dbismut**
We built [this dashboard](http://dashboard.sidlee.com) as an internal project to celebrate the 6th anniversary of our agency, personally my first public development :)

### CODE REVIEW

**Comment by fastdivision** [comment]
This is freakin' awesome! Love the design. Thanks for your contribution :+1:

**Comment by dbismut** [comment]
Thanks! It doesn't show on the site, did I miss something maybe? Sorry about this!

**Comment by dbismut** [comment]
@fastdivision sorry, any news?

**Comment by fastdivision** [comment]
@dbismut Should be up now! Going to set up CI/CD soon so it automatically publishes.

**Comment by dbismut** [comment]
Yes! Thanks so much!

**Pull request merged**
